name: Update

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron: "0 10 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync version with upstream
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Version
        id: version
        run: |
          LATEST=$(curl -sL https://api.github.com/repos/icloud-photos-downloader/icloud_photos_downloader/releases |
            jq .  | grep tag_name | head -n 1 | cut -d'"' -f4 | tr -d 'v'
          )
          sed -i 's/^\(version: \).*$/\1'"$LATEST"'/' snap/snapcraft.yaml
          echo "version=$LATEST" >> $GITHUB_OUTPUT

      - name: Detect changes
        id: changes
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes detected"
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup LXD
        if: ${{ steps.changes.outputs.updated == 'true' }}
        uses: canonical/setup-lxd@v0.1.2

      - name: Ensure snap builds
        if: ${{ steps.changes.outputs.updated == 'true' }}
        run: |
          sudo snap install --classic snapcraft
          snapcraft --verbose

      - name: Commit changes
        if: ${{ steps.changes.outputs.updated == 'true' }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: bump icloudpd to version ${{ steps.version.outputs.version }}"
          git push

      - name: Open issue if failed
        if: ${{ failure() && steps.changes.outputs.updated == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue create --title "Auto-update to version \`${{ steps.version.outputs.version }}\` failed" --body "Attempted to update snap automatically, but build failed. See: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} for details."
